---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: omnios-r151008
    driver:
      box_url: https://vagrantcloud.com/omniti/omnios-r151008/version/1/provider/virtualbox.box

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[postgres_libs]
      - recipe[postmodern::default]
    attributes:
